-- ============================================================================
-- CTI Table Existence Check
-- ============================================================================
-- PURPOSE: Verify which CTI tables exist in this database before anonymization
-- RUN AS: Any user with SELECT on ALL_TABLES
-- ============================================================================

SET PAGESIZE 200
SET LINESIZE 150
SET HEADING ON
SET FEEDBACK OFF
COLUMN table_name FORMAT A35
COLUMN owner FORMAT A10

PROMPT
PROMPT ====================================================================
PROMPT CTI TABLE EXISTENCE CHECK
PROMPT ====================================================================
PROMPT

-- Check all CTI tables from the reference list
SELECT 
 t.table_name AS "Table Name",
 CASE WHEN a.table_name IS NOT NULL THEN 'YES' ELSE 'NO' END AS "Exists?",
 a.owner AS "Owner",
 a.num_rows AS "Row Count"
FROM (
 -- CM tables (Cash Management)
 SELECT 'CM_ACCOUNT_OF_BKSTMT_FILE' AS table_name FROM dual UNION ALL
 SELECT 'CM_ARCHIVED_FORECAST' FROM dual UNION ALL
 SELECT 'CM_BKSTMT_FILE_CONFIG' FROM dual UNION ALL
 SELECT 'CM_BSI_BANK_STATEMENT' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_ACCOUNTS' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_HEADER' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL' FROM dual UNION ALL
 SELECT 'CM_FLI_FLOW' FROM dual UNION ALL
 SELECT 'CM_FLOW_TO_PAY_RULES' FROM dual UNION ALL
 SELECT 'CM_FOI_FORECAST' FROM dual UNION ALL
 SELECT 'CM_FORECAST' FROM dual UNION ALL
 SELECT 'CM_PAYT_PAYMENT' FROM dual UNION ALL
 SELECT 'CM_POOLING_CONVENTION' FROM dual UNION ALL
 SELECT 'CM_POOLING_METHOD' FROM dual UNION ALL
 SELECT 'CM_PROCESS' FROM dual UNION ALL
 SELECT 'CMS_FILE_BKD' FROM dual UNION ALL
 SELECT 'CM_CMS_EXCEPTIONS' FROM dual UNION ALL
 -- DM tables (Deal Management)
 SELECT 'DM_HEDGE_REQUEST' FROM dual UNION ALL
 SELECT 'DM_HR_AUTOVALID_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_CTRP_MAP' FROM dual UNION ALL
 SELECT 'DM_HR_CUTOFF_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_LIMIT_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_PTF_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_QUOTATION' FROM dual UNION ALL
 -- TP tables (Third Party)
 SELECT 'TP_BUSINESS_PROFILE' FROM dual UNION ALL
 SELECT 'TP_COMM_ENTITY_DIM' FROM dual UNION ALL
 SELECT 'TP_CONTACT' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_BANKACCOUNT' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_CTRP' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_ENTITY' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_PTF' FROM dual UNION ALL
 SELECT 'TP_POS_SNAPSHOT' FROM dual UNION ALL
 SELECT 'TP_POS_SNAPSHOT_RESULTS' FROM dual UNION ALL
 SELECT 'TP_TENANT_ENTITY' FROM dual UNION ALL
 SELECT 'TP_USERS' FROM dual UNION ALL
 SELECT 'TP_WV_MAILING_RULE' FROM dual UNION ALL
 SELECT 'TP_WV_TRANSITION_RULE' FROM dual UNION ALL
 -- UAA tables
 SELECT 'UAA_USERS' FROM dual
) t
LEFT JOIN all_tables a ON UPPER(a.table_name) = t.table_name
ORDER BY t.table_name;

PROMPT
PROMPT ====================================================================
PROMPT CTI COLUMN CHECK (key columns only)
PROMPT ====================================================================
PROMPT

-- Check if specific columns exist in key tables
SELECT 
 expected.tbl AS table_name,
 expected.col AS column_name,
 CASE WHEN c.column_name IS NOT NULL THEN 'EXISTS' ELSE 'MISSING' END AS status
FROM (
 -- CM tables key columns
 SELECT 'CM_ACCOUNT_OF_BKSTMT_FILE' AS tbl, 'ENTITY' AS col FROM dual UNION ALL
 SELECT 'CM_ACCOUNT_OF_BKSTMT_FILE', 'ACCOUNT' FROM dual UNION ALL
 SELECT 'CM_ACCOUNT_OF_BKSTMT_FILE', 'BANK' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_HEADER', 'ENTITY' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_HEADER', 'CONTREPARTIE' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_HEADER', 'MASTER_ACCOUNT' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL', 'ENTITY' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL', 'CONTREPARTIE' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL', 'COMPTE_TIERS' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL', 'CLEARING_MEMBER' FROM dual UNION ALL
 SELECT 'CM_FLI_FLOW', 'ENTITY' FROM dual UNION ALL
 SELECT 'CM_FLI_FLOW', 'COUNTERPARTY' FROM dual UNION ALL
 SELECT 'CM_FORECAST', 'ENTITY' FROM dual UNION ALL
 SELECT 'CM_FORECAST', 'BANK' FROM dual UNION ALL
 SELECT 'CM_PAYT_PAYMENT', 'PORTFOLIO' FROM dual UNION ALL
 SELECT 'CM_PAYT_PAYMENT', 'CPTY_ACCOUNT_CODE' FROM dual UNION ALL
 -- DM tables key columns
 SELECT 'DM_HEDGE_REQUEST', 'ENTITY' FROM dual UNION ALL
 SELECT 'DM_HEDGE_REQUEST', 'COUNTERPARTY' FROM dual UNION ALL
 SELECT 'DM_HR_QUOTATION', 'ENTITY' FROM dual UNION ALL
 SELECT 'DM_HR_QUOTATION', 'ACCOUNT' FROM dual UNION ALL
 -- TP tables key columns
 SELECT 'TP_COMM_ENTITY_DIM', 'ENTITY' FROM dual UNION ALL
 SELECT 'TP_COMM_ENTITY_DIM', 'PHONE' FROM dual UNION ALL
 SELECT 'TP_CONTACT', 'ENTITY' FROM dual UNION ALL
 SELECT 'TP_POS_SNAPSHOT_RESULTS', 'EMAIL' FROM dual UNION ALL
 SELECT 'TP_WV_MAILING_RULE', 'ENTITY' FROM dual UNION ALL
 SELECT 'TP_WV_MAILING_RULE', 'FIRSTNAME' FROM dual UNION ALL
 -- UAA tables
 SELECT 'UAA_USERS', 'EMAIL' FROM dual UNION ALL
 SELECT 'UAA_USERS', 'FIRSTNAME' FROM dual
) expected
LEFT JOIN all_tab_columns c 
 ON UPPER(c.table_name) = expected.tbl 
 AND UPPER(c.column_name) = expected.col
ORDER BY expected.tbl, expected.col;

PROMPT
PROMPT ====================================================================
PROMPT SUMMARY: CTI Tables to Anonymize
PROMPT ====================================================================
PROMPT

SELECT 
 t.table_name,
 CASE WHEN a.table_name IS NOT NULL THEN 'EXISTS - WILL BE PROCESSED' 
 ELSE 'DOES NOT EXIST - WILL BE SKIPPED' 
 END AS action
FROM (
 SELECT 'CM_ACCOUNT_OF_BKSTMT_FILE' AS table_name FROM dual UNION ALL
 SELECT 'CM_ARCHIVED_FORECAST' FROM dual UNION ALL
 SELECT 'CM_BKSTMT_FILE_CONFIG' FROM dual UNION ALL
 SELECT 'CM_BSI_BANK_STATEMENT' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_ACCOUNTS' FROM dual UNION ALL
 SELECT 'CM_CASH_CONCENT_HEADER' FROM dual UNION ALL
 SELECT 'CM_DEAL_DEAL' FROM dual UNION ALL
 SELECT 'CM_FLI_FLOW' FROM dual UNION ALL
 SELECT 'CM_FLOW_TO_PAY_RULES' FROM dual UNION ALL
 SELECT 'CM_FOI_FORECAST' FROM dual UNION ALL
 SELECT 'CM_FORECAST' FROM dual UNION ALL
 SELECT 'CM_PAYT_PAYMENT' FROM dual UNION ALL
 SELECT 'CM_POOLING_CONVENTION' FROM dual UNION ALL
 SELECT 'CM_POOLING_METHOD' FROM dual UNION ALL
 SELECT 'CM_PROCESS' FROM dual UNION ALL
 SELECT 'CMS_FILE_BKD' FROM dual UNION ALL
 SELECT 'CM_CMS_EXCEPTIONS' FROM dual UNION ALL
 SELECT 'DM_HEDGE_REQUEST' FROM dual UNION ALL
 SELECT 'DM_HR_AUTOVALID_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_CTRP_MAP' FROM dual UNION ALL
 SELECT 'DM_HR_CUTOFF_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_LIMIT_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_PTF_BKD' FROM dual UNION ALL
 SELECT 'DM_HR_QUOTATION' FROM dual UNION ALL
 SELECT 'TP_BUSINESS_PROFILE' FROM dual UNION ALL
 SELECT 'TP_COMM_ENTITY_DIM' FROM dual UNION ALL
 SELECT 'TP_CONTACT' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_BANKACCOUNT' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_CTRP' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_ENTITY' FROM dual UNION ALL
 SELECT 'TP_DATA_PROFILE_PTF' FROM dual UNION ALL
 SELECT 'TP_POS_SNAPSHOT' FROM dual UNION ALL
 SELECT 'TP_POS_SNAPSHOT_RESULTS' FROM dual UNION ALL
 SELECT 'TP_TENANT_ENTITY' FROM dual UNION ALL
 SELECT 'TP_USERS' FROM dual UNION ALL
 SELECT 'TP_WV_MAILING_RULE' FROM dual UNION ALL
 SELECT 'TP_WV_TRANSITION_RULE' FROM dual UNION ALL
 SELECT 'UAA_USERS' FROM dual
) t
LEFT JOIN all_tables a ON UPPER(a.table_name) = t.table_name
ORDER BY t.table_name;

EXIT;