-- ============================================================================
-- Load Custom Inclusions from CSV into temp table
-- ============================================================================
-- PURPOSE: Parse inclusions.csv and populate atrace.anon_inclusions
-- Called by start_anonymous.bat BEFORE running anonymization
--
-- This script is generated/called by the batch file after parsing the CSV.
-- The batch file reads inclusions.csv, filters comments, and generates
-- INSERT statements that are spooled to this file or executed directly.
--
-- USAGE: Called automatically by start_anonymous.bat
-- Or manually: @sql\load_inclusions.sql
--
-- VERSION: 1.0.0 (2026-08-07)
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK OFF

PROMPT
PROMPT === Loading custom inclusions from inclusions.csv ===
PROMPT

-- Create table if not exists
DECLARE
 v_exists NUMBER;
BEGIN
 SELECT COUNT(*) INTO v_exists 
 FROM all_tables 
 WHERE owner = 'ATRACE' AND table_name = 'ANON_INCLUSIONS';
 
 IF v_exists = 0 THEN
 EXECUTE IMMEDIATE '
 CREATE TABLE atrace.anon_inclusions (
 table_name VARCHAR2(128) NOT NULL,
 column_name VARCHAR2(128) NOT NULL,
 anon_type VARCHAR2(10) NOT NULL,
 notes VARCHAR2(500),
 processed VARCHAR2(1) DEFAULT ''N'',
 process_msg VARCHAR2(500),
 CONSTRAINT pk_anon_inclusions PRIMARY KEY (table_name, column_name)
 )';
 DBMS_OUTPUT.PUT_LINE(' Created table atrace.anon_inclusions');
 ELSE
 -- Clear previous run data
 EXECUTE IMMEDIATE 'DELETE FROM atrace.anon_inclusions';
 COMMIT;
 DBMS_OUTPUT.PUT_LINE(' Cleared previous inclusions data');
 END IF;
END;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON atrace.anon_inclusions TO op;

-- ============================================================================
-- INSERT statements will be generated by batch script and appended below
-- Format: INSERT INTO atrace.anon_inclusions (table_name, column_name, anon_type, notes)
-- VALUES ('table', 'column', 'TYPE', 'notes');
-- ============================================================================

-- PLACEHOLDER: Batch script will append INSERT statements here
-- Example:
-- INSERT INTO atrace.anon_inclusions (table_name, column_name, anon_type, notes) 
-- VALUES ('new_table', 'entity_col', 'E', 'Added for v3.0');
-- COMMIT;

DECLARE
 v_count NUMBER;
BEGIN
 SELECT COUNT(*) INTO v_count FROM atrace.anon_inclusions;
 IF v_count > 0 THEN
 DBMS_OUTPUT.PUT_LINE(' Loaded ' || v_count || ' custom inclusion(s)');
 ELSE
 DBMS_OUTPUT.PUT_LINE(' No custom inclusions loaded (file empty or all commented)');
 END IF;
END;
/

PROMPT